//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchEvaluationWpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatchEvaluationWpf.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среднее время.
        /// </summary>
        public static string AverageTimeColumn {
            get {
                return ResourceManager.GetString("AverageTimeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string CountColumn {
            get {
                return ResourceManager.GetString("CountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время работы:.
        /// </summary>
        public static string GlobalTimeLbl {
            get {
                return ResourceManager.GetString("GlobalTimeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процент от общего времени обработки.
        /// </summary>
        public static string GlobalTimePercentColumn {
            get {
                return ResourceManager.GetString("GlobalTimePercentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать файл....
        /// </summary>
        public static string LoadBtn {
            get {
                return ResourceManager.GetString("LoadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция.
        /// </summary>
        public static string OperationColumn {
            get {
                return ResourceManager.GetString("OperationColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прогноз остатка времени обработки:.
        /// </summary>
        public static string RemainingTimeLbl {
            get {
                return ResourceManager.GetString("RemainingTimeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить расчет.
        /// </summary>
        public static string StartBtn {
            get {
                return ResourceManager.GetString("StartBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить расчет.
        /// </summary>
        public static string StopBtn {
            get {
                return ResourceManager.GetString("StopBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество обработанных выражений:.
        /// </summary>
        public static string TotalCountLbl {
            get {
                return ResourceManager.GetString("TotalCountLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общее время.
        /// </summary>
        public static string TotalTimeColumn {
            get {
                return ResourceManager.GetString("TotalTimeColumn", resourceCulture);
            }
        }
    }
}
